/* constantc.c
 * relevant constants exposed via Lua puffs module
 *
 * <insert BSD license here> */

#include <lua.h>
#include <lauxlib.h>

#include <puffs.h>
#include <sys/mount.h>
#include <sys/vnode.h>
#include <sys/extattr.h>
#include <dirent.h>
#include <errno.h>

// macro to push a constant
// assumes that lua_State *L exists
#define DEFCONST_INT(name) lua_pushstring(L, #name); lua_pushinteger(L, name); lua_settable(L, -3);

int luapuffs_install_constants(lua_State *L)
{
  // top of stack = library table built by caller
  //lua_pushstring(L, "ENOENT"); lua_pushinteger(L, ENOENT); lua_settable(L, -3);

  // errno values
  DEFCONST_INT(EPERM);
  DEFCONST_INT(ENOENT);
  DEFCONST_INT(ESRCH);
  DEFCONST_INT(EINTR);
  DEFCONST_INT(EIO);
  DEFCONST_INT(ENXIO);
  DEFCONST_INT(E2BIG);
  DEFCONST_INT(ENOEXEC);
  DEFCONST_INT(EBADF);
  DEFCONST_INT(ECHILD);
  DEFCONST_INT(EDEADLK);
  DEFCONST_INT(ENOMEM);
  DEFCONST_INT(EACCES);
  DEFCONST_INT(EFAULT);
  DEFCONST_INT(ENOTBLK);
  DEFCONST_INT(EBUSY);
  DEFCONST_INT(EEXIST);
  DEFCONST_INT(EXDEV);
  DEFCONST_INT(ENODEV);
  DEFCONST_INT(ENOTDIR);
  DEFCONST_INT(EISDIR);
  DEFCONST_INT(EINVAL);
  DEFCONST_INT(ENFILE);
  DEFCONST_INT(EMFILE);
  DEFCONST_INT(ENOTTY);
  DEFCONST_INT(ETXTBSY);
  DEFCONST_INT(EFBIG);
  DEFCONST_INT(ENOSPC);
  DEFCONST_INT(ESPIPE);
  DEFCONST_INT(EROFS);
  DEFCONST_INT(EMLINK);
  DEFCONST_INT(EPIPE);
  DEFCONST_INT(EDOM);
  DEFCONST_INT(ERANGE);
  DEFCONST_INT(EAGAIN);
  DEFCONST_INT(EWOULDBLOCK);
  DEFCONST_INT(EINPROGRESS);
  DEFCONST_INT(EALREADY);
  DEFCONST_INT(ENOTSOCK);
  DEFCONST_INT(EDESTADDRREQ);
  DEFCONST_INT(EMSGSIZE);
  DEFCONST_INT(EPROTOTYPE);
  DEFCONST_INT(ENOPROTOOPT);
  DEFCONST_INT(EPROTONOSUPPORT);
  DEFCONST_INT(ESOCKTNOSUPPORT);
  DEFCONST_INT(EOPNOTSUPP);
  DEFCONST_INT(EPFNOSUPPORT);
  DEFCONST_INT(EAFNOSUPPORT);
  DEFCONST_INT(EADDRINUSE);
  DEFCONST_INT(EADDRNOTAVAIL);
  DEFCONST_INT(ENETDOWN);
  DEFCONST_INT(ENETUNREACH);
  DEFCONST_INT(ENETRESET);
  DEFCONST_INT(ECONNABORTED);
  DEFCONST_INT(ECONNRESET);
  DEFCONST_INT(ENOBUFS);
  DEFCONST_INT(EISCONN);
  DEFCONST_INT(ENOTCONN);
  DEFCONST_INT(ESHUTDOWN);
  DEFCONST_INT(ETOOMANYREFS);
  DEFCONST_INT(ETIMEDOUT);
  DEFCONST_INT(ECONNREFUSED);
  DEFCONST_INT(ELOOP);
  DEFCONST_INT(ENAMETOOLONG);
  DEFCONST_INT(EHOSTDOWN);
  DEFCONST_INT(EHOSTUNREACH);
  DEFCONST_INT(ENOTEMPTY);
  DEFCONST_INT(EPROCLIM);
  DEFCONST_INT(EUSERS);
  DEFCONST_INT(EDQUOT);
  DEFCONST_INT(ESTALE);
  DEFCONST_INT(EREMOTE);
  DEFCONST_INT(EBADRPC);
  DEFCONST_INT(ERPCMISMATCH);
  DEFCONST_INT(EPROGUNAVAIL);
  DEFCONST_INT(EPROGMISMATCH);
  DEFCONST_INT(EPROCUNAVAIL);
  DEFCONST_INT(ENOLCK);
  DEFCONST_INT(ENOSYS);
  DEFCONST_INT(EFTYPE);
  DEFCONST_INT(EAUTH);
  DEFCONST_INT(ENEEDAUTH);
  DEFCONST_INT(EIDRM);
  DEFCONST_INT(ENOMSG);
  DEFCONST_INT(EOVERFLOW);
  DEFCONST_INT(EILSEQ);
  DEFCONST_INT(ENOTSUP);
  DEFCONST_INT(ECANCELED);
  DEFCONST_INT(EBADMSG);
  DEFCONST_INT(ENODATA);
  DEFCONST_INT(ENOSR);
  DEFCONST_INT(ENOSTR);
  DEFCONST_INT(ETIME);
  DEFCONST_INT(ENOATTR);
  DEFCONST_INT(EMULTIHOP);
  DEFCONST_INT(ENOLINK);
  DEFCONST_INT(EPROTO);
  DEFCONST_INT(EOWNERDEAD);
  DEFCONST_INT(ENOTRECOVERABLE);

  // puffs constants
  DEFCONST_INT(PUFFS_NODE_REMOVED);
  DEFCONST_INT(PUFFS_VNOVAL);
  DEFCONST_INT(PUFFS_IO_APPEND);
  DEFCONST_INT(PUFFS_IO_NDELAY);
  DEFCONST_INT(PUFFS_VEXEC);
  DEFCONST_INT(PUFFS_VWRITE);
  DEFCONST_INT(PUFFS_VREAD);
  DEFCONST_INT(PUFFS_FSYNC_DATAONLY);
  DEFCONST_INT(PUFFS_FSYNC_CACHE);
  DEFCONST_INT(PUFFS_SETATTR_FAF);
  DEFCONST_INT(PUFFS_WRITE_FAF);
  DEFCONST_INT(PUFFS_EXTATTR_LIST_LENPREFIX);
  DEFCONST_INT(PUFFS_STATE_BEFOREMOUNT);
  DEFCONST_INT(PUFFS_STATE_RUNNING);
  DEFCONST_INT(PUFFS_STATE_UNMOUNTING);
  DEFCONST_INT(PUFFS_STATE_UNMOUNTED);
  DEFCONST_INT(PUFFS_FLAG_BUILDPATH);
  DEFCONST_INT(PUFFS_FLAG_OPDUMP);
  DEFCONST_INT(PUFFS_FLAG_HASHPATH);
  DEFCONST_INT(PUFFS_FLAG_PNCOOKIE);    // you don't need to set this in luapuffs
  DEFCONST_INT(PUFFS_FLAG_MASK);
  DEFCONST_INT(PUFFSDEV_BLOCK);
  DEFCONST_INT(PUFFSDEV_NONBLOCK);
  DEFCONST_INT(DENT_DOT);
  DEFCONST_INT(DENT_DOTDOT);
 
  // flags that can be passed to um:mount()
  DEFCONST_INT(MNT_RDONLY);
  DEFCONST_INT(MNT_SYNCHRONOUS);
  DEFCONST_INT(MNT_NOEXEC);
  DEFCONST_INT(MNT_NOSUID);
  DEFCONST_INT(MNT_NODEV);
  DEFCONST_INT(MNT_UNION);
  DEFCONST_INT(MNT_ASYNC);
  DEFCONST_INT(MNT_NOCOREDUMP);
  DEFCONST_INT(MNT_RELATIME);
  DEFCONST_INT(MNT_IGNORE);
  DEFCONST_INT(MNT_NFS4ACLS);
  DEFCONST_INT(MNT_DISCARD);
  DEFCONST_INT(MNT_EXTATTR);
  DEFCONST_INT(MNT_LOG);
  DEFCONST_INT(MNT_NOATIME);
  DEFCONST_INT(MNT_AUTOMOUNTED);
  DEFCONST_INT(MNT_SYMPERM);
  DEFCONST_INT(MNT_NODEVMTIME);
  DEFCONST_INT(MNT_SOFTDEP);
  DEFCONST_INT(MNT_POSIX1EACLS);
  DEFCONST_INT(MNT_ACLS);
  DEFCONST_INT(MNT_BASIC_FLAGS);
  DEFCONST_INT(MNT_UPDATE);
  DEFCONST_INT(MNT_RELOAD);
  DEFCONST_INT(MNT_FORCE);
  DEFCONST_INT(MNT_GETARGS);
  DEFCONST_INT(MNT_OP_FLAGS);
  DEFCONST_INT(MNT_WAIT);
  DEFCONST_INT(MNT_NOWAIT);
  DEFCONST_INT(MNT_LAZY);

  // vnode types
  DEFCONST_INT(VNON);
  DEFCONST_INT(VREG);
  DEFCONST_INT(VDIR);
  DEFCONST_INT(VBLK);
  DEFCONST_INT(VCHR);
  DEFCONST_INT(VLNK);
  DEFCONST_INT(VSOCK);
  DEFCONST_INT(VFIFO);
  DEFCONST_INT(VBAD);

  // dirent file types
  DEFCONST_INT(DT_UNKNOWN);
  DEFCONST_INT(DT_FIFO);
  DEFCONST_INT(DT_CHR);
  DEFCONST_INT(DT_DIR);
  DEFCONST_INT(DT_BLK);
  DEFCONST_INT(DT_REG);
  DEFCONST_INT(DT_LNK);
  DEFCONST_INT(DT_SOCK);
  DEFCONST_INT(DT_WHT);

  // namei operation types
  DEFCONST_INT(NAMEI_LOOKUP);
  DEFCONST_INT(NAMEI_CREATE);
  DEFCONST_INT(NAMEI_DELETE);
  DEFCONST_INT(NAMEI_RENAME);
  DEFCONST_INT(NAMEI_OPMASK);

  // extattr operation types
  DEFCONST_INT(EXTATTR_CMD_START);
  DEFCONST_INT(EXTATTR_CMD_STOP);

  return 0;
}

